# Config file for CelebA dataset (200k)

output_dir: '/data/pphui8/checkpoints/StyleGAN.pytorch/ckp_celeba_6'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: '/home/pphui8/data/img_align_celeba'
  folder: False
  resolution: 128
sched:
  epochs: [2,4,4,4,4,8]
